version: "3.8"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    volumes:
      - .:/go/src/app
      # - ./.env:/go/src/app/.env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
